config/routes.rb
Rails.application.routes.draw do



  resources :events do
    resources :agenda_entries
    resources :speakers
    resources :sponsors
  end

  resources :cards
  resources :admins
  resources :categories
  resources :messages
  resources :boxes
  resources :galleries
  resources :certifications
  resources :newsletters
  resources :carousels
  resources :events
  resources :articles
  resources :abouts
  resources :contacts
  resources :faqs
  resources :links

  root 'static_pages#index'
  get 'static_pages/index'

  devise_scope :user do
    get "/login",  :to => "devise/sessions#new"
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'dashboard' => 'dashboard#index' # dashboard controller needs user authentication
  get 'certificates' => 'static_pages#certificates'
  get 'news' => 'static_pages#news'
  get 'entities' => 'static_pages#entities'
  get 'about' => 'static_pages#about'
  get 'search' => 'static_pages#search'
  get 'publications' => 'static_pages#publications'
  get 'contact' => 'static_pages#contact'
  get 'event' => 'static_pages#event'
  get 'statistics' => 'static_pages#statistics'
  get 'events_list' => 'static_pages#events_list'
  get 'multimedia' => 'static_pages#multimedia'
  get 'faq' => 'static_pages#faq'
end

app/models/faq.rb
class Faq < ApplicationRecord
  include PgSearch
  multisearchable :against => [:question, :answer]
  validates :question, :answer, presence: true
  validates :question, length: { minimum: 10, maximum: 100 }
  validates :answer, length: { minimum: 10, maximum: 600 }
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]
  before_action :verify_if_user_can_manage?, except: [:index, :show]
  layout "dashboard"

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all.order(:created_at).reverse_order
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to faqs_url, notice: 'La pregunta fue creada exitosamente' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to faqs_url, notice: 'La pregunta fue editada exitosamente' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'La pregunta fue eliminada exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:question, :answer)
    end

    def verify_if_user_can_manage?
      redirect_to dashboard_path unless current_user.admin.can_manage_faq
    end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form.html.erb
    <%= bootstrap_form_for(faq) do |f| %>
      <% if faq.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

          <ul>
          <% faq.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.text_field :question, class: 'form-control', label: "Pregunta" %>
      </div>

      <div class="field">
        <%= f.text_area :answer, class: 'form-control', rows: 5, label: "Respuesta" %>
      </div>

      <div class="actions">
        <div class="text-center">
          <%= f.submit 'Aceptar', class: "btn btn-asoban" %>
          <%= link_to "Volver", '/faqs', class: "btn btn-asoban-inverse" %>
        </div>
      </div>
    <% end %>

app/views/faqs/edit.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="box">
      <div class="box-header">
				<h2>Editar pregunta</h2>
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        <%= render 'form', faq: @faq %>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/faqs/index.html.erb
<h1 class="text-center">Preguntas Frecuentes</h1>

<% if notice.present? %>
  <div class="alert alert-asoban">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <div id="notice"> <%= notice %> </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <div class="box">
      <div class="box-header">
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>Pregunta</th>
              <th>Respuesta</th>
              <th colspan="2"></th>
            </tr>
          </thead>

          <tbody>
            <% @faqs.each do |faq| %>
              <tr>
                <td><%= faq.question %></td>
                <td><%= faq.answer %></td>
                <td><%= link_to 'Editar', edit_faq_path(faq), class: 'btn btn-asoban' %></td>
                <td><%= link_to 'Eliminar', faq, method: :delete, data: { confirm: '¿Está seguro que desea eliminar este registro?' }, class: 'btn btn-asoban-inverse' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        <%= link_to 'Nueva Pregunta', new_faq_path, class: 'btn btn-asoban' %>
      </div>
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/faqs/new.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="box">
      <div class="box-header">
				<h2>Editar pregunta</h2>
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        <%= render 'form', faq: @faq %>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @faq.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @faq.answer %>
</p>

<%= link_to 'Editar', edit_faq_path(@faq) %> |
<%= link_to 'Atrás', faqs_path %>