config/routes.rb
Rails.application.routes.draw do



  resources :events do
    resources :agenda_entries
    resources :speakers
    resources :sponsors
  end

  resources :cards
  resources :admins
  resources :categories
  resources :messages
  resources :boxes
  resources :galleries
  resources :certifications
  resources :newsletters
  resources :carousels
  resources :events
  resources :articles
  resources :abouts
  resources :contacts
  resources :faqs
  resources :links

  root 'static_pages#index'
  get 'static_pages/index'

  devise_scope :user do
    get "/login",  :to => "devise/sessions#new"
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'dashboard' => 'dashboard#index' # dashboard controller needs user authentication
  get 'certificates' => 'static_pages#certificates'
  get 'news' => 'static_pages#news'
  get 'entities' => 'static_pages#entities'
  get 'about' => 'static_pages#about'
  get 'search' => 'static_pages#search'
  get 'publications' => 'static_pages#publications'
  get 'contact' => 'static_pages#contact'
  get 'event' => 'static_pages#event'
  get 'statistics' => 'static_pages#statistics'
  get 'events_list' => 'static_pages#events_list'
  get 'multimedia' => 'static_pages#multimedia'
  get 'faq' => 'static_pages#faq'
end

app/models/carousel.rb
class Carousel < ApplicationRecord
	has_attached_file :pic1, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :pic1, content_type: /\Aimage\/.*\z/

	has_attached_file :pic2, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :pic2, content_type: /\Aimage\/.*\z/

  	has_attached_file :pic3, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :pic3, content_type: /\Aimage\/.*\z/
end

app/controllers/carousels_controller.rb
class CarouselsController < ApplicationController
  before_action :set_carousel, only: [:show, :edit, :update, :destroy]
  before_action :verify_if_user_can_manage?, except: [:index, :show]
  layout 'dashboard'

  # GET /carousels
  # GET /carousels.json
  def index
    @carousels = Carousel.all.order(:created_at).reverse_order
  end

  # GET /carousels/1
  # GET /carousels/1.json
  def show
  end

  # GET /carousels/new
  def new
    @carousel = Carousel.new
  end

  # GET /carousels/1/edit
  def edit
  end

  # POST /carousels
  # POST /carousels.json
  def create
    @carousel = Carousel.new(carousel_params)

    respond_to do |format|
      if @carousel.save
        format.html { redirect_to carousels_url, notice: 'Carrusel creado exitosamente' }
        format.json { render :show, status: :created, location: @carousel }
      else
        format.html { render :new }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carousels/1
  # PATCH/PUT /carousels/1.json
  def update
    respond_to do |format|
      if @carousel.update(carousel_params)
        format.html { redirect_to carousels_url, notice: 'Carrusel actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @carousel }
      else
        format.html { render :edit }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carousels/1
  # DELETE /carousels/1.json
  def destroy
    @carousel.destroy
    respond_to do |format|
      format.html { redirect_to carousels_url, notice: 'Carrusel eliminado exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carousel
      @carousel = Carousel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carousel_params
      params.require(:carousel).permit(:pic1, :pic2, :pic3)
    end

    def verify_if_user_can_manage?
      redirect_to dashboard_path unless current_user.admin.can_manage_carousel
    end
end

app/helpers/carousels_helper.rb
module CarouselsHelper
end

app/views/carousels/_form.html.erb
<%= bootstrap_form_for(carousel, html: { multipart: true }) do |f| %>
  <% if carousel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carousel.errors.count, "error") %> prohibited this carousel from being saved:</h2>

      <ul>
      <% carousel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :pic1, label: 'Imagen 1' %>
  </div>

  <div class="field">
    <%= f.file_field :pic2, label: 'Imagen 2' %>
  </div>

  <div class="field">
    <%= f.file_field :pic3, label: 'Imagen 3' %>
  </div>

  <div class="actions">
    <%= f.submit 'Aceptar', class: 'btn btn-asoban' %>
    <%= link_to 'Volver', '/carousels', class: 'btn btn-asoban-inverse' %>
  </div>
<% end %>

app/views/carousels/edit.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="box">
      <div class="box-header">
				<h2>Editar Carrusel</h2>
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        <%= render 'form', carousel: @carousel %>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/carousels/index.html.erb
<h1 class="text-center">Carrusel</h1>

<% if notice.present? %>
  <div class="alert alert-asoban">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <div id="notice"> <%= notice %> </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <div class="box">
      <div class="box-header">
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>Imagen 1</th>
              <th>Imagen 2</th>
              <th>Imagen 3</th>
              <th colspan="2"></th>
            </tr>
          </thead>

          <tbody>
            <% @carousels.each do |carousel| %>
              <tr>
                <td>carousel.pic1_file_name</td>
                <td>carousel.pic2_file_name</td>
                <td>carousel.pic3_file_name</td>
                <td><%= link_to 'Editar', edit_carousel_path(carousel), class: 'btn btn-asoban' %></td>
                <td><%= link_to 'Eliminar', carousel, method: :delete, data: { confirm: '¿Está seguro que desea eliminar este registro?' }, class: 'btn btn-asoban-inverse' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        <%= link_to 'Nuevo carrusel', new_carousel_path, class: "btn btn-asoban" %>
      </div>
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/carousels/new.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="box">
      <div class="box-header">
				<h2>Nuevo Carrusel</h2>
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        <%= render 'form', carousel: @carousel %>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/carousels/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_carousel_path(@carousel) %> |
<%= link_to 'Back', carousels_path %>