config/routes.rb
Rails.application.routes.draw do



  resources :events do
    resources :agenda_entries
    resources :speakers
    resources :sponsors
  end

  resources :cards
  resources :admins
  resources :categories
  resources :messages
  resources :boxes
  resources :galleries
  resources :certifications
  resources :newsletters
  resources :carousels
  resources :events
  resources :articles
  resources :abouts
  resources :contacts
  resources :faqs
  resources :links

  root 'static_pages#index'
  get 'static_pages/index'

  devise_scope :user do
    get "/login",  :to => "devise/sessions#new"
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'dashboard' => 'dashboard#index' # dashboard controller needs user authentication
  get 'certificates' => 'static_pages#certificates'
  get 'news' => 'static_pages#news'
  get 'entities' => 'static_pages#entities'
  get 'about' => 'static_pages#about'
  get 'search' => 'static_pages#search'
  get 'publications' => 'static_pages#publications'
  get 'contact' => 'static_pages#contact'
  get 'event' => 'static_pages#event'
  get 'statistics' => 'static_pages#statistics'
  get 'events_list' => 'static_pages#events_list'
  get 'multimedia' => 'static_pages#multimedia'
  get 'faq' => 'static_pages#faq'
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy]
  before_action :verify_if_user_can_manage?, except: [:index, :show]
  layout 'dashboard'

  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all.order(:created_at).reverse_order
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to newsletters_url, notice: 'Boletín creado exitosamente' }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to @newsletter, notice: 'Boletín actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to newsletters_url, notice: 'Boletín eliminado exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:title, :description)
    end

    def verify_if_user_can_manage?
      redirect_to dashboard_path unless current_user.admin.can_manage_newsletter
    end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.erb
<%= bootstrap_form_for(newsletter) do |f| %>
  <% if newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% newsletter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, label: 'Título' %>
  </div>

  <div class="field">
    <%= f.text_area :description, label: 'Contenido' %>
  </div>

  <div class="actions">
    <%= f.submit 'Aceptar', class: 'btn btn-asoban' %>
    <%= link_to 'Volver', '/newsletters', class: 'btn btn-asoban-inverse' %>
  </div>
<% end %>

app/views/newsletters/edit.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="box">
      <div class="box-header">
				<h2>Editar boletín</h2>
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        <%= render 'form', newsletter: @newsletter %>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/newsletters/index.html.erb
<h1 class="text-center">Boletín</h1>

<% if notice.present? %>
  <div class="alert alert-asoban">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <div id="notice"> <%= notice %> </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <div class="box">
      <div class="box-header">
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>Título</th>
              <th>Contenido</th>
              <th colspan="2"></th>
            </tr>
          </thead>

          <tbody>
            <% @newsletters.each do |newsletter| %>
              <tr>
                <td><%= newsletter.title %></td>
                <td><%= newsletter.description %></td>
                <td><%= link_to 'Eliminar', newsletter, method: :delete, data: { confirm: '¿Está seguro que desea eliminar este registro?' }, class: 'btn btn-asoban-inverse' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        <%= link_to 'Nuevo Boletín', new_newsletter_path, class: 'btn btn-asoban' %>
      </div>
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/newsletters/new.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="box">
      <div class="box-header">
				<h2>Nuevo Boletín</h2>
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        <%= render 'form', newsletter: @newsletter %>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @newsletter.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @newsletter.description %>
</p>

<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>